spring.application.name=chango
# Database Config
spring.h2.console.enabled=true
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Mail config
mailjet.apikey.public=${MAILJET_PUBLIC_API_KEY}
mailjet.apikey.private=${MAILJET_PRIVATE_API_KEY}
